backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:

  - label: "Content"
    name: "content"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "src/data/navigation.json"
        fields:
          - {label: "About", name: "about", widget: "markdown"}
          - {label: "Contact", name: "contact", widget: "markdown"}
          - {label: "Commercial", name: "commercial", widget: "markdown"}

  - name: "project"
    label: "Project"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Type", name: "type", widget: "select", options: ["creative", "commercial"]}
      - {label: Image, name: image, widget: image}
      - {label: HoverImage, name: imageHover, widget: image}
      - {label: Slides, name: slides, widget: list, fields: [{label: "Type", name: type, widget: select, options: ["image", "3dobject","video"]}, {label: "Title", name: title, widget: string}, {label: "File", name: file, widget: file},{label: "URL", name: url, widget: string}]}
      - {label: "Body", name: "body", widget: "markdown"}
